### ISSUE TITLE
Pivot migration generated with error

### ISSUE THREAD

**Issue by Behinder** [laracasts/Laravel-5-Generators-Extended#161] opened 2019-03-10 20:18 UTC
- Laravel Version: 5.8
- PHP Version: 7.3
- Laravel-5-Generators-Extended Version:
- Command:
php artisan make:migration:pivot
### Description:

Trying to run migration I got 
syntax error, unexpected '\' (T_NS_SEPARATOR), expecting '{'

my file looks like this:

```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class App\ extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('kaciki_song', function (Blueprint $table) {
            $table->integer('kaciki_id')->unsigned()->index();
            $table->foreign('kaciki_id')->references('id')->on('kaciki')->onDelete('cascade');
            $table->integer('song_id')->unsigned()->index();
            $table->foreign('song_id')->references('id')->on('songs')->onDelete('cascade');
            $table->primary(['kaciki_id', 'song_id']);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('kaciki_song');
    }
}
```

**Comment by elistone** [comment] 2019-03-31 19:37
The issue seems to be a problem with generating the class name. I fixed mine manually by just setting up the name. By the looks of things you could set yours to be something like: `CreateKacikiSongPivotTable`

**Comment by SaintPeter** [comment] 2019-04-13 17:51
I had this same issue.
Laravel Version: 5.5
PHP Version: 7.1
Laravel-5-Generators-Extended Version: 1.1
Command:
php artisan make:migration:pivot teams judge_awards

output:
```php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class App\ extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('judge_award_team', function (Blueprint $table) {
            $table->integer('judge_award_id')->unsigned()->index();
            $table->foreign('judge_award_id')->references('id')->on('judge_awards')->onDelete('cascade');
            $table->integer('team_id')->unsigned()->index();
            $table->foreign('team_id')->references('id')->on('teams')->onDelete('cascade');
            $table->primary(['judge_award_id', 'team_id']);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('judge_award_team');
    }
}
```

I was able to fix it by manually adding a class name of `CreateJudgeAwardTeamPivotTable` to line 6:
```php
class CreateJudgeAwardTeamPivotTable extends Migration
```

**Comment by armagedan** [comment] 2019-05-30 02:58
The problem is at
    Class App\
Rename that to an actual class and you’re good to go
Does this happen when you use only ‘make:migration:pivot’ ?

**Comment by SaintPeter** [comment] 2019-05-30 03:01
> The problem is at
> Class App
> Rename that to an actual class and you’re good to go

I did rename and fix.  The issue is that the class name should be automatically generated.

> Does this happen when you use only ‘make:migration:pivot’ ?

What would be the point of that?  The whole idea is to have the pivot generated for the two classes/tables listed.

**Comment by armagedan** [comment] 2019-05-30 03:10
@saintpeter I’m not familiar with make:migration:pivot. Are you using a third party package? By convention, laravel expects the migration name to be in alphabetical order. In your case, I think the judge_table should come before team. In your example you have given the opposite. Please let me know

**Comment by SaintPeter** [comment] 2019-05-30 03:20
@armagedan Maybe you're confused about where you are?

This project, laracasts/Laravel-5-Generators-Extended, adds some additional generators/functionality to the standard Laravel make:* commands.  One of those commands, `make:migration:pivot`, generates a properly formatted migration for a pivot between two tables.  While this can be done manually, it can be a tad tricky to do properly.

This issue thread is about a defect in that specific functionality:  when automatically generating the migration, the class name is not being properly generated, as depicted above.  I think everyone else here understands the nature of the issue, we're just hoping that the author (or "someone") will track down the source of the problem and apply a patch.

So, yes, we understand what the problem with the generated code is.  We want this generator to be fixed.

**Comment by armagedan** [comment] 2019-05-30 03:24
My bad. Then you should note that this package is no longer managed or updated. It doesn’t seem like a troubling fix. Feel free to fork and make changes on your own.

**Comment by SaintPeter** [comment] 2019-05-30 03:27
> Then you should note that this package is no longer managed or updated.

How can you tell?  Aside from a lack of recent commits (last one was roughly a year back), there is no obvious indication in the Readme that it's not being maintained.

**Comment by armagedan** [comment] 2019-05-30 03:42
Then lets hope there is a commit to fix this issue

**Comment by coolsam726** [comment] 2019-07-20 01:07
The issue seems to exist in the latest release (1.1.4), but I realized that it is fixed in the master branch. So while installing on composer I specified the master branch instead:

```bash
composer require laracasts/generators:master --dev
```
This fixed my issue :smile:

**Comment by tabacitu** [comment] 2019-08-17 08:57
Hi @coolsam726 - thanks for letting us know. 

Just tagged version 1.1.5 - so you should be able to install it normally and still get the fixes. Don't know about future fixes though - unfortunately I don't think I'll be able to put much time into this repo.

Cheers!

**Closed by tabacitu** 2019-08-17 08:57 UTC
