### ISSUE TITLE
Incorrect pivot table name

### ISSUE THREAD

**Issue by juliusvdijk** [laracasts/Laravel-5-Generators-Extended#153] opened 2018-01-23 11:05 UTC
- Laravel Version: 5.4.36
- PHP Version: 7.1
- Laravel-5-Generators-Extended Version: 1.1.4
- Command: php artisan make:migration:pivot products product_sets

### Description:
Laravel expects a pivot table name of 'product_product_set'.
The command creates the pivot table name of 'product_set_product'.

### Steps To Reproduce:
1. Create 2 models, Product and ProductSet. Add a belongsToMany between them.
2. Run `php artisan make:migration:pivot products product_sets`
3. Run `php artisan migrate`
4. Try to access the belongsToMany relation.

**Comment by bogdankharchenko** [comment] 2018-01-26 15:11
I created a PR for this, https://github.com/laracasts/Laravel-5-Generators-Extended/pull/154

**Comment by cristianuibar** [comment] 2018-02-25 12:03
I can confirm this is still an issue. Any ETA for merging the fix from @bogdankharchenko ?

**Comment by bogdankharchenko** [comment] 2018-02-25 20:25
@cristianuibar I'm not sure when it'll get merged ---- I don't have those privileges.  Feel free to pull my repo in the meantime, https://github.com/bogdankharchenko/Laravel-5-Generators-Extended 

add git repo to composer.json, 
`"repositories": [
    {
      "type": "git",
      "url": "https://github.com/bogdankharchenko/Laravel-5-Generators-Extended"
    }
]`
and change your versioning to,     

`"laracasts/generators": "dev-develop"`

**Comment by michealradionov** [comment] 2018-04-09 16:07
thanks, @bogdankharchenko

**Comment by Behinder** [comment] 2019-03-11 13:57
I use @bogdankharchenko  repo and I still have similar issue.
I have two models: Corner and Song - the tables are called "corners" and "songs".
If i create pivot with "php artisan make:migration:pivot corner song" (I've read in everyplace this is proper naming convention) resulting code is:
```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCornerSongPivotTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('corner_song', function (Blueprint $table) {
            $table->integer('corner_id')->unsigned()->index();
            $table->foreign('corner_id')->references('id')->on('corner')->onDelete('cascade');
            $table->integer('song_id')->unsigned()->index();
            $table->foreign('song_id')->references('id')->on('song')->onDelete('cascade');
            $table->primary(['corner_id', 'song_id']);
            $table->integer('program_id')->unsigned;

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('corner_song');
    }
}
```
Problem is primary keys are referencing wrong table name then, because neither "corner" nor "song" exists.

**Comment by amberlampsio** [comment] 2019-03-11 14:03
Install dev-master ---

`composer require laracasts/generators:dev-master`

Should work just fine, Just tried it.

**Comment by Behinder** [comment] 2019-03-11 14:16
Ok it's working only if you remove Bogdan repo.
when I left it, and added dev-master it created wrong class name in header.
after composer upgrade pivot was created correctly. I'm writing it in case   someone else find this problematic

**Comment by tabacitu** [comment] 2020-03-08 11:17
PR got merged, so I'll close this issue. Let me know if this is still a problem and I'll reopen. Thanks for pitching in, everyone! Cheers!

**Closed by tabacitu** 2020-03-08 11:17 UTC
