### ISSUE TITLE
How to generate "$table->string('title',100)"

### ISSUE THREAD

**Issue by rockyx128** [laracasts/Laravel-5-Generators-Extended#152] opened 2018-01-23 01:54 UTC
- Laravel Version: 5.4.30
- PHP Version:7.2.0
- Laravel-5-Generators-Extended Version:latest
- Command:I dont know and want to know^_^

### Description:

Im freshman in Laravel ,and learn Laravel 5.4.

I find this great tool.

But how to generate "$table->string('title',100)"

**Comment by rockyx128** [comment] 2018-01-23 01:55
Forgive me for my poor English.
 Aha~

**Comment by sean-swannie** [comment] 2018-12-12 02:35
Based on a "quick" look at the code of the SchemaParser functions it looks like you can pass the length after the type declaration. It looks like the parser will split the schema string that you passed into the seperate fields which are then parsed into segments. Each segment is then checked for attributes and options which is then assigned to the variables "name", "type", "arguments" or "options" fields which are used to build the stubs.

For Example: 
--schema"title:string(100) email:string:unique another:integer some:string(15):unique" 
will be split into the fields...
1. title:string(100), and then into name = title, type = string, arguments = 100, options = null
2. email:string:unique, and then into name = email, type = string, arguments = null, options = unique
3. another:integer, and then into name = another, type = integer, arguments = null, options = null 
4. some:string(15):unique, and then into name = some, type = string, arguments = 15, options = unique

**Comment by tabacitu** [comment] 2020-03-08 10:05
Yup what @sean-swannie said 😄 Closing this since I'm pretty sure it's not a bug.

Cheers!

**Closed by tabacitu** 2020-03-08 10:05 UTC
