### ISSUE TITLE
Pivot not working correctly

### ISSUE THREAD

**Issue by betteryourweb** [laracasts/Laravel-5-Generators-Extended#45] opened 2015-05-31 08:33 UTC
When generating pivot table, the generator is putting ->unsigned() before >index() and is causing the index not to be created at the right time (I'm guessing) and causes a failure on creating the foreign keys. If I reorder and put the ->index() method first in the change, it creates the index and foreign keys

**Comment by Houbsi** [comment] 2015-07-14 08:15
I had the same issue,

but the issue is that you enter the "Model" Name in singular:
```
make:migration:pivot User Company
```
But in the created migration it uses as tablename for the foreign key the "singular"name instead of the default "multiple"name.

This:
```
$table->foreign('company_id')->references('id')->on('company')->onDelete('cascade');
```

Should be:
```
$table->foreign('company_id')->references('id')->on('companys')->onDelete('cascade');
````

**Comment by tabacitu** [comment] 2020-03-08 08:46
Hi there, I see the code is now ```$table->foreign('{{columnTwo}}_id')->references('id')->on('{{tableTwo}}')->onDelete('cascade');``` so I assume this has been fixed sometime between 2015 and 2020 😃 

Closing. Thanks!

**Closed by tabacitu** 2020-03-08 08:46 UTC
