### ISSUE TITLE
ambiguous class name

### ISSUE THREAD

**Issue by tushar3006** [laracasts/Laravel-5-Generators-Extended#62] opened 2015-07-27 15:45 UTC
bug:
if a table name has an underscore , then the class name created in the migration for that table also includes an unexpected underscore.

e.g
php artisan migration:make:pivot locality time_slot
results in creation of piviot table create_locality_time_slot_pivot_table
as:
class CreateLocalityTime_slotPivotTable extends Migration
{ public function up()
    {
        Schema::create('locality_time_slot', function(Blueprint $table) {
            $table->integer('locality_id')->unsigned()->index();
            $table->foreign('locality_id')->references('id')->on('localities')->onDelete('cascade');

....}}

**Comment by fbidu** [comment] 2016-01-12 15:06
I can confirm that I was affected by this bug as well

**Comment by jrsickles** [comment] 2016-01-29 18:00
This also affected me

**Comment by tabacitu** [comment] 2020-03-08 11:01
I believe this has been fixed since the issue was posted. Let me know if you're still encountering this issue and we'll reopen. But I've run ```php artisan make:migration:pivot product product_descriptions``` and I got this:

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateProductProductDescriptionPivotTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_product_description', function (Blueprint $table) {
            $table->unsignedBigInteger('product_id')->index();
            $table->foreign('product_id')->references('id')->on('product')->onDelete('cascade');
            $table->unsignedBigInteger('product_description_id')->index();
            $table->foreign('product_description_id')->references('id')->on('product_descriptions')->onDelete('cascade');
            $table->primary(['product_id', 'product_description_id']);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_product_description');
    }
}

```

So I think it's fixed now.
Cheers!

**Closed by tabacitu** 2020-03-08 11:01 UTC
